-- ============================================================
-- BIOPUREX · 0002 · Catálogo inicial (GENERADO por scripts/generar-semilla.ts — no editar a mano)
-- Aromas, categorías, 43 productos (uno por tamaño) con sus variantes por aroma,
-- stock inicial de ejemplo (30 por variante; 0 en las marcadas como agotadas) y la configuración.
-- PRECIOS Y DATOS BANCARIOS SON DE EJEMPLO hasta que el cliente los confirme.
-- Ejecutar DESPUÉS de 0001_esquema_inicial.sql.
-- ============================================================

insert into public.aromas (id, nombre, color, orden) values
  ('lavanda', 'Lavanda', '#7B4FC9', 0),
  ('citronella', 'Citronella', '#F2C230', 1),
  ('manzanacanela', 'Manzana Canela', '#C8202F', 2),
  ('limon', 'Limón', '#C9D62B', 3),
  ('pino', 'Pino', '#2E8B3A', 4),
  ('manzanaverde', 'Manzana Verde', '#8CC63F', 5),
  ('cereza', 'Cereza', '#D7263D', 6),
  ('fresh', 'Fresh', '#4FB3E8', 7),
  ('passionfruit', 'Passionfruit', '#8E3FA8', 8),
  ('espuma', 'Espuma Limpiadora', '#2A9DB5', 9),
  ('sweetfusion', 'Sweet Fusion', '#E0457B', 10),
  ('sunnypop', 'Sunny Pop', '#6CC3E8', 11),
  ('sweettouch', 'Sweet Touch', '#EE8FB5', 12),
  ('uva', 'Uva', '#6B3FA0', 13),
  ('mandarina', 'Mandarina', '#F28C28', 14),
  ('vainilla', 'Vainilla', '#E8C07A', 15),
  ('carronuevo', 'Carro Nuevo', '#8A94A6', 16);

insert into public.categorias (id, nombre, corto, img, tinte, oscura, orden) values
  ('hogar', 'Limpieza del hogar', 'Hogar', 'des_lav_gal', 'lavanda', false, 0),
  ('lavanderia', 'Lavandería', 'Lavandería', 'biowash_sweet', 'sweetfusion', false, 1),
  ('cocina', 'Cocina y manos', 'Cocina y manos', 'manos_cereza', 'cereza', false, 2),
  ('alimenticio', 'Grado alimenticio', 'Grado alimenticio', 'biodish', 'espuma', false, 3),
  ('aromatizantes', 'Aromatizantes BIOSCENT', 'Aromatizantes', 'scent_mandarina', 'mandarina', false, 4),
  ('auto', 'Línea automotriz', 'Automotriz', 'foam_gal', null, true, 5),
  ('articulos', 'Artículos de limpieza', 'Artículos', 'escoba', null, false, 6),
  ('dispensadores', 'Dispensadores', 'Dispensadores', 'disp_jabon', null, false, 7);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('desinfectante-galon', 'desinfectante', 'Desinfectante Multiusos Galón', 'Desinfectante Multiusos', 'Galón', 'hogar', 95.00, 'Mantén tus espacios limpios y libres de gérmenes con nuestro Limpiador Desinfectante. Ideal para pisos y superficies diversas.', array['Elimina el 99.9% de bacterias y gérmenes.', 'Limpieza profunda en diversas superficies.', 'Fórmula efectiva: no deja residuos, garantizando limpieza total.', 'Ideal para uso en hogares, oficinas e instituciones.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, array['mas']::text[], 'lavanda', '{"pino":"Aroma refrescante: el perfume de pino proporciona una sensación de limpieza y frescura.","manzanaverde":"Aroma refrescante: el perfume de manzana verde proporciona una sensación fresca y revitalizante."}'::jsonb, 0);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'desinfectante-galon'), 'lavanda', 'lavanda', 'Lavanda', '/img/des_lav_gal.webp', 'DESINFECTANTE-GALON-LAVANDA', 30, 0),
  ((select id from public.productos where slug = 'desinfectante-galon'), 'citronella', 'citronella', 'Citronella', '/img/des_cit_gal.webp', 'DESINFECTANTE-GALON-CITRONELLA', 30, 1),
  ((select id from public.productos where slug = 'desinfectante-galon'), 'manzanacanela', 'manzanacanela', 'Manzana Canela', '/img/des_mc_gal.webp', 'DESINFECTANTE-GALON-MANZANACANELA', 30, 2),
  ((select id from public.productos where slug = 'desinfectante-galon'), 'limon', 'limon', 'Limón', '/img/des_lim_gal.webp', 'DESINFECTANTE-GALON-LIMON', 30, 3),
  ((select id from public.productos where slug = 'desinfectante-galon'), 'pino', 'pino', 'Pino', '/img/des_pino_gal.webp', 'DESINFECTANTE-GALON-PINO', 0, 4),
  ((select id from public.productos where slug = 'desinfectante-galon'), 'manzanaverde', 'manzanaverde', 'Manzana Verde', '/img/des_mv_gal.webp', 'DESINFECTANTE-GALON-MANZANAVERDE', 30, 5);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('desinfectante-litro', 'desinfectante', 'Desinfectante Multiusos Litro', 'Desinfectante Multiusos', 'Litro', 'hogar', 35.00, 'Mantén tus espacios limpios y libres de gérmenes con nuestro Limpiador Desinfectante. Ideal para pisos y superficies diversas.', array['Elimina el 99.9% de bacterias y gérmenes.', 'Limpieza profunda en diversas superficies.', 'Fórmula efectiva: no deja residuos, garantizando limpieza total.', 'Ideal para uso en hogares, oficinas e instituciones.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, array['mas']::text[], 'lavanda', '{"pino":"Aroma refrescante: el perfume de pino proporciona una sensación de limpieza y frescura.","manzanaverde":"Aroma refrescante: el perfume de manzana verde proporciona una sensación fresca y revitalizante."}'::jsonb, 1);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'desinfectante-litro'), 'lavanda', 'lavanda', 'Lavanda', '/img/des_lav_lt.webp', 'DESINFECTANTE-LITRO-LAVANDA', 30, 0),
  ((select id from public.productos where slug = 'desinfectante-litro'), 'citronella', 'citronella', 'Citronella', '/img/des_cit_lt.webp', 'DESINFECTANTE-LITRO-CITRONELLA', 0, 1),
  ((select id from public.productos where slug = 'desinfectante-litro'), 'manzanacanela', 'manzanacanela', 'Manzana Canela', '/img/des_mc_lt.webp', 'DESINFECTANTE-LITRO-MANZANACANELA', 30, 2),
  ((select id from public.productos where slug = 'desinfectante-litro'), 'limon', 'limon', 'Limón', '/img/des_lim_lt.webp', 'DESINFECTANTE-LITRO-LIMON', 30, 3),
  ((select id from public.productos where slug = 'desinfectante-litro'), 'pino', 'pino', 'Pino', '/img/des_pino_lt.webp', 'DESINFECTANTE-LITRO-PINO', 0, 4),
  ((select id from public.productos where slug = 'desinfectante-litro'), 'manzanaverde', 'manzanaverde', 'Manzana Verde', '/img/des_mv_lt.webp', 'DESINFECTANTE-LITRO-MANZANAVERDE', 30, 5);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('desengrasante-galon', 'desengrasante', 'Desengrasante Multiusos pH Neutro Galón', 'Desengrasante Multiusos pH Neutro', 'Galón', 'hogar', 120.00, 'Nuestro Desengrasante Multiusos pH Neutro está diseñado para una limpieza efectiva y segura en cualquier tipo de superficie. Su fórmula balanceada elimina grasa, aceite y suciedad sin dañar materiales delicados ni afectar la piel.', array['Elimina grasa, aceite y suciedad.', 'No daña materiales delicados ni afecta la piel.', 'Ideal para uso doméstico, comercial e industrial.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, array['nuevo']::text[], 'manzanaverde', '{}'::jsonb, 2);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'desengrasante-galon'), 'unica', null, 'Galón', '/img/desen_gal.webp', 'DESENGRASANTE-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('desengrasante-740-ml', 'desengrasante', 'Desengrasante Multiusos pH Neutro 740 ml', 'Desengrasante Multiusos pH Neutro', '740 ml', 'hogar', 55.00, 'Nuestro Desengrasante Multiusos pH Neutro está diseñado para una limpieza efectiva y segura en cualquier tipo de superficie. Su fórmula balanceada elimina grasa, aceite y suciedad sin dañar materiales delicados ni afectar la piel.', array['Elimina grasa, aceite y suciedad.', 'No daña materiales delicados ni afecta la piel.', 'Ideal para uso doméstico, comercial e industrial.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, array['nuevo']::text[], 'manzanaverde', '{}'::jsonb, 3);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'desengrasante-740-ml'), 'unica', null, '740 ml', '/img/desen_740.webp', 'DESENGRASANTE-740-ML-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('antisarro', 'antisarro', 'Limpiador Antisarro en Gel 3 en 1 Litro', 'Limpiador Antisarro en Gel 3 en 1', 'Litro', 'hogar', 65.00, 'Eficaz gel desincrustante que utiliza una combinación de detergentes y ácidos para quitar fácilmente las manchas en el inodoro provocadas por moho, hongos y acumulaciones minerales como calcio, magnesio, hierro y otros.', array['100% removedor de sarro', '99.9% removedor de gérmenes', 'Desodoriza']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], true, false, '{}'::text[], 'mandarina', '{}'::jsonb, 4);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'antisarro'), 'unica', null, 'Litro', '/img/antisarro.webp', 'ANTISARRO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('cloro-galon', 'cloro', 'Cloro Biopurex Galón', 'Cloro Biopurex', 'Galón', 'hogar', 70.00, 'Con su fórmula poderosa, nuestro cloro de alta concentración es tu aliado definitivo contra las bacterias, virus y gérmenes. Eliminando el 99.9% de las amenazas en segundos.', array['Cloro de alta concentración.', 'Elimina el 99.9% de bacterias, virus y gérmenes en segundos.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], true, false, array['mas']::text[], 'fresh', '{}'::jsonb, 5);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'cloro-galon'), 'unica', null, 'Galón', '/img/cloro_gal.webp', 'CLORO-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('cloro-litro', 'cloro', 'Cloro Biopurex Litro', 'Cloro Biopurex', 'Litro', 'hogar', 25.00, 'Con su fórmula poderosa, nuestro cloro de alta concentración es tu aliado definitivo contra las bacterias, virus y gérmenes. Eliminando el 99.9% de las amenazas en segundos.', array['Cloro de alta concentración.', 'Elimina el 99.9% de bacterias, virus y gérmenes en segundos.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], true, false, array['mas']::text[], 'fresh', '{}'::jsonb, 6);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'cloro-litro'), 'unica', null, 'Litro', '/img/cloro_lt.webp', 'CLORO-LITRO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('bioglass-galon', 'bioglass', 'Limpiavidrios BIOGLASS Galón', 'Limpiavidrios BIOGLASS', 'Galón', 'hogar', 110.00, 'Logra que tus vidrios luzcan impecables y relucientes con la extraordinaria fórmula ecoamigable de Bioglass. Diseñada para ofrecer una limpieza fácil y rápida, esta solución no solo elimina la suciedad y las manchas, sino que también deja un brillo total que hará que tus ventanas, espejos y superficies de vidrio destaquen.', array['Fórmula ecoamigable.', 'Elimina la suciedad y las manchas.', 'Brillo total en ventanas, espejos y superficies de vidrio.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, '{}'::text[], 'fresh', '{}'::jsonb, 7);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'bioglass-galon'), 'unica', null, 'Galón', '/img/bioglass_gal.webp', 'BIOGLASS-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('bioglass-740-ml', 'bioglass', 'Limpiavidrios BIOGLASS 740 ml', 'Limpiavidrios BIOGLASS', '740 ml', 'hogar', 50.00, 'Logra que tus vidrios luzcan impecables y relucientes con la extraordinaria fórmula ecoamigable de Bioglass. Diseñada para ofrecer una limpieza fácil y rápida, esta solución no solo elimina la suciedad y las manchas, sino que también deja un brillo total que hará que tus ventanas, espejos y superficies de vidrio destaquen.', array['Fórmula ecoamigable.', 'Elimina la suciedad y las manchas.', 'Brillo total en ventanas, espejos y superficies de vidrio.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, '{}'::text[], 'fresh', '{}'::jsonb, 8);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'bioglass-740-ml'), 'unica', null, '740 ml', '/img/bioglass_740.webp', 'BIOGLASS-740-ML-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('biowash', 'biowash', 'Detergente Líquido BIOWASH Galón', 'Detergente Líquido BIOWASH', 'Galón', 'lavanderia', 185.00, 'Detergente líquido de alto rendimiento formulado para limpiar profundamente las prendas, eliminando suciedad y malos olores mientras cuida las fibras y los colores. Su fórmula genera una limpieza eficiente, dejando la ropa fresca, suave y con una agradable fragancia duradera.', array['Limpia profundamente las prendas.', 'Elimina suciedad y malos olores.', 'Cuida las fibras y los colores.', 'Fragancia agradable y duradera.']::text[], array['Agrega la dosis indicada en la etiqueta según el tamaño de la carga.', 'Para manchas difíciles, aplica directo y deja actuar antes de lavar.']::text[], false, false, array['mas']::text[], 'espuma', '{}'::jsonb, 9);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'biowash'), 'espuma', 'espuma', 'Espuma Limpiadora', '/img/biowash_espuma.webp', 'BIOWASH-ESPUMA', 30, 0),
  ((select id from public.productos where slug = 'biowash'), 'sweetfusion', 'sweetfusion', 'Sweet Fusion', '/img/biowash_sweet.webp', 'BIOWASH-SWEETFUSION', 30, 1);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('polvo', 'polvo', 'Detergente en Polvo Industrial', 'Detergente en Polvo Industrial', 'Presentación por confirmar', 'lavanderia', null, 'Detergente en polvo de alto rendimiento, formulado para la limpieza profunda y remoción eficaz de suciedad, manchas y grasa en prendas de uso diario e industrial.', array['Remoción eficaz de suciedad, manchas y grasa.', 'Ideal para lavanderías, hoteles, restaurantes, industrias y uso institucional.']::text[], array['Agrega la dosis indicada en la etiqueta según el tamaño de la carga.', 'Para manchas difíciles, aplica directo y deja actuar antes de lavar.']::text[], false, true, '{}'::text[], 'espuma', '{}'::jsonb, 10);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'polvo'), 'unica', null, 'Presentación por confirmar', '/img/polvo.webp', 'POLVO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('biosoft', 'biosoft', 'Suavizante de Telas BIOSOFT Galón', 'Suavizante de Telas BIOSOFT', 'Galón', 'lavanderia', 150.00, 'El suavizante de telas Biopurex está formulado para ofrecer un cuidado superior a tus prendas, brindando una suavidad excepcional y una fragancia fresca que perdura.', array['Cuidado superior para tus prendas.', 'Suavidad excepcional.', 'Fragancia fresca que perdura.']::text[], array['Agrega la dosis indicada en la etiqueta según el tamaño de la carga.', 'Para manchas difíciles, aplica directo y deja actuar antes de lavar.']::text[], false, false, '{}'::text[], 'sunnypop', '{}'::jsonb, 11);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'biosoft'), 'sunnypop', 'sunnypop', 'Sunny Pop', '/img/biosoft_sunny.webp', 'BIOSOFT-SUNNYPOP', 30, 0),
  ((select id from public.productos where slug = 'biosoft'), 'sweettouch', 'sweettouch', 'Sweet Touch', '/img/biosoft_sweet.webp', 'BIOSOFT-SWEETTOUCH', 30, 1);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('jabon-manos', 'jabon-manos', 'Jabón de Manos', 'Jabón de Manos', 'Presentación por confirmar', 'cocina', 140.00, 'Descubre el cuidado y la suavidad que tu piel merece con nuestra exclusiva línea de jabones para manos. Formulados con fragancias irresistibles.', array['Cuidado y suavidad para tu piel.', 'Fragancias irresistibles.']::text[], array['Aplica una pequeña cantidad en la esponja o en las manos húmedas.', 'Frota hasta formar espuma y enjuaga con abundante agua.']::text[], false, false, '{}'::text[], 'cereza', '{}'::jsonb, 12);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'jabon-manos'), 'cereza', 'cereza', 'Cereza', '/img/manos_cereza.webp', 'JABON-MANOS-CEREZA', 30, 0),
  ((select id from public.productos where slug = 'jabon-manos'), 'fresh', 'fresh', 'Fresh', '/img/manos_fresh.webp', 'JABON-MANOS-FRESH', 30, 1),
  ((select id from public.productos where slug = 'jabon-manos'), 'passionfruit', 'passionfruit', 'Passionfruit', '/img/manos_passion.webp', 'JABON-MANOS-PASSIONFRUIT', 30, 2);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('jabon-platos-liquido', 'jabon-platos-liquido', 'Jabón de Platos Líquido Galón', 'Jabón de Platos Líquido', 'Galón', 'cocina', 130.00, 'Descubre nuestro jabón de platos con fórmula mejorada, diseñado para ofrecer una limpieza superior. Ahora enriquecido con un potente desengrasante, elimina con facilidad la grasa más difícil.', array['Fórmula mejorada.', 'Enriquecido con un potente desengrasante.', 'Elimina con facilidad la grasa más difícil.']::text[], array['Aplica una pequeña cantidad en la esponja o en las manos húmedas.', 'Frota hasta formar espuma y enjuaga con abundante agua.']::text[], false, false, '{}'::text[], 'manzanaverde', '{}'::jsonb, 13);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'jabon-platos-liquido'), 'unica', null, 'Galón', '/img/platos_liq.webp', 'JABON-PLATOS-LIQUIDO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('jabon-platos-crema', 'jabon-platos-crema', 'Jabón de Platos en Crema', 'Jabón de Platos en Crema', 'Unidad', 'cocina', 45.00, 'Descubre nuestro jabón de platos con fórmula mejorada, diseñado para ofrecer una limpieza superior. Ahora enriquecido con un potente desengrasante, elimina con facilidad la grasa más difícil.', array['Fórmula mejorada.', 'Enriquecido con un potente desengrasante.', 'Elimina con facilidad la grasa más difícil.']::text[], array['Aplica una pequeña cantidad en la esponja o en las manos húmedas.', 'Frota hasta formar espuma y enjuaga con abundante agua.']::text[], false, false, '{}'::text[], 'manzanaverde', '{}'::jsonb, 14);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'jabon-platos-crema'), 'unica', null, 'Unidad', '/img/platos_crema.webp', 'JABON-PLATOS-CREMA-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('biosoap', 'biosoap', 'BIOSOAP Jabón de Manos Galón', 'BIOSOAP Jabón de Manos', 'Galón', 'alimenticio', 160.00, 'BIOSOAP & BIODISH son jabones líquidos de alta calidad diseñados para brindar una limpieza eficaz y confiable. Formulados con agentes limpiadores y espumantes de alto desempeño, ayudan a remover suciedad, grasa y residuos de manera eficiente. BIOSOAP proporciona una limpieza suave y efectiva para las manos.', array['Limpieza suave y efectiva para las manos.', 'Agentes limpiadores y espumantes de alto desempeño.']::text[], array['Aplica una pequeña cantidad en la esponja o en las manos húmedas.', 'Frota hasta formar espuma y enjuaga con abundante agua.']::text[], false, false, array['nuevo']::text[], 'fresh', '{}'::jsonb, 15);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'biosoap'), 'unica', null, 'Galón', '/img/biosoap.webp', 'BIOSOAP-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('biodish', 'biodish', 'BIODISH Jabón de Platos Galón', 'BIODISH Jabón de Platos', 'Galón', 'alimenticio', 160.00, 'BIOSOAP & BIODISH son jabones líquidos de alta calidad diseñados para brindar una limpieza eficaz y confiable. BIODISH está formulado para uso en áreas de manipulación de alimentos.', array['Para áreas de manipulación de alimentos.', 'Remueve suciedad, grasa y residuos de manera eficiente.']::text[], array['Aplica una pequeña cantidad en la esponja o en las manos húmedas.', 'Frota hasta formar espuma y enjuaga con abundante agua.']::text[], false, false, '{}'::text[], 'espuma', '{}'::jsonb, 16);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'biodish'), 'unica', null, 'Galón', '/img/biodish.webp', 'BIODISH-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('foodsafe', 'foodsafe', 'Desengrasante FOOD SAFE Galón', 'Desengrasante FOOD SAFE', 'Galón', 'alimenticio', 210.00, 'Es un desengrasante biodegradable líquido formulado con agentes activos que actúan rápidamente para disolver y remover grasa, residuos secos de alimentos y suciedad incrustada.', array['Biodegradable.', 'Disuelve y remueve grasa, residuos secos de alimentos y suciedad incrustada.']::text[], array['Aplica el producto directo o diluido en agua, según la etiqueta.', 'Limpia la superficie con un paño, esponja o trapeador.', 'Deja actuar unos minutos y enjuaga si es necesario.']::text[], false, false, '{}'::text[], 'mandarina', '{}'::jsonb, 17);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'foodsafe'), 'unica', null, 'Galón', '/img/foodsafe.webp', 'FOODSAFE-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('bioscent', 'bioscent', 'Aromatizante BIOSCENT', 'Aromatizante BIOSCENT', 'Spray', 'aromatizantes', 85.00, '', '{}'::text[], array['Rocía al aire o sobre telas a unos 30 cm de distancia.']::text[], false, false, '{}'::text[], 'carronuevo', '{}'::jsonb, 18);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'bioscent'), 'carronuevo', 'carronuevo', 'Carro Nuevo', '/img/scent_carro.webp', 'BIOSCENT-CARRONUEVO', 30, 0),
  ((select id from public.productos where slug = 'bioscent'), 'uva', 'uva', 'Uva', '/img/scent_uva.webp', 'BIOSCENT-UVA', 30, 1),
  ((select id from public.productos where slug = 'bioscent'), 'uva-2', 'uva', 'Uva · envase 2', '/img/scent_uva2.webp', 'BIOSCENT-UVA-2', 30, 2),
  ((select id from public.productos where slug = 'bioscent'), 'mandarina', 'mandarina', 'Mandarina', '/img/scent_mandarina.webp', 'BIOSCENT-MANDARINA', 30, 3),
  ((select id from public.productos where slug = 'bioscent'), 'vainilla', 'vainilla', 'Vainilla', '/img/scent_vainilla.webp', 'BIOSCENT-VAINILLA', 30, 4);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('biofoam-galon', 'biofoam', 'Shampoo de Espuma Activa BIOFOAM X Galón', 'Shampoo de Espuma Activa BIOFOAM X', 'Galón', 'auto', 260.00, 'BIOFOAM X es un shampoo de espuma activa de alto rendimiento, formulado especialmente para hidrolavadoras, cañón de espuma y túneles de carwash. Su tecnología espumante genera una espuma abundante, estable y de gran cobertura, ayudando a remover suciedad mientras mejora la experiencia visual del lavado.', array['Para hidrolavadora, cañón de espuma y carwash.', 'Espuma abundante, estable y de gran cobertura.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, array['nuevo']::text[], 'cereza', '{}'::jsonb, 19);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'biofoam-galon'), 'unica', null, 'Galón', '/img/foam_gal.webp', 'BIOFOAM-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('biofoam-20-l', 'biofoam', 'Shampoo de Espuma Activa BIOFOAM X 20 L', 'Shampoo de Espuma Activa BIOFOAM X', '20 L', 'auto', 1250.00, 'BIOFOAM X es un shampoo de espuma activa de alto rendimiento, formulado especialmente para hidrolavadoras, cañón de espuma y túneles de carwash. Su tecnología espumante genera una espuma abundante, estable y de gran cobertura, ayudando a remover suciedad mientras mejora la experiencia visual del lavado.', array['Para hidrolavadora, cañón de espuma y carwash.', 'Espuma abundante, estable y de gran cobertura.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, array['nuevo']::text[], 'cereza', '{}'::jsonb, 20);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'biofoam-20-l'), 'unica', null, '20 L', '/img/foam_20.webp', 'BIOFOAM-20-L-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('shampoo-carros-galon', 'shampoo-carros', 'Shampoo para Carros Standard Galón', 'Shampoo para Carros Standard', 'Galón', 'auto', 180.00, 'Limpia, protege y da un brillo excepcional a tu vehículo con el shampoo para carros Biopurex. Su fórmula de alta calidad elimina la suciedad más difícil mientras cuida la pintura y deja un acabado reluciente. Espuma abundante y fácil de enjuagar.', array['Cuida la pintura.', 'Acabado reluciente.', 'Espuma abundante y fácil de enjuagar.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'mandarina', '{}'::jsonb, 21);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'shampoo-carros-galon'), 'unica', null, 'Galón', '/img/shampoo_gal.webp', 'SHAMPOO-CARROS-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('shampoo-carros-20-l', 'shampoo-carros', 'Shampoo para Carros Standard 20 L', 'Shampoo para Carros Standard', '20 L', 'auto', 850.00, 'Limpia, protege y da un brillo excepcional a tu vehículo con el shampoo para carros Biopurex. Su fórmula de alta calidad elimina la suciedad más difícil mientras cuida la pintura y deja un acabado reluciente. Espuma abundante y fácil de enjuagar.', array['Cuida la pintura.', 'Acabado reluciente.', 'Espuma abundante y fácil de enjuagar.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'mandarina', '{}'::jsonb, 22);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'shampoo-carros-20-l'), 'unica', null, '20 L', '/img/shampoo_20.webp', 'SHAMPOO-CARROS-20-L-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('llantas-740-ml', 'llantas', 'Abrillantador de Llantas 740 ml', 'Abrillantador de Llantas', '740 ml', 'auto', 75.00, 'Fórmula avanzada que limpia, restaura y protege, dejando tus llantas con un brillo intenso y un negro profundo. Combate suciedad y crea una capa protectora duradera para un acabado impecable.', array['Brillo intenso y negro profundo.', 'Capa protectora duradera.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'fresh', '{}'::jsonb, 23);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'llantas-740-ml'), 'unica', null, '740 ml', '/img/llantas_740.webp', 'LLANTAS-740-ML-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('llantas-galon', 'llantas', 'Abrillantador de Llantas Galón', 'Abrillantador de Llantas', 'Galón', 'auto', 220.00, 'Fórmula avanzada que limpia, restaura y protege, dejando tus llantas con un brillo intenso y un negro profundo. Combate suciedad y crea una capa protectora duradera para un acabado impecable.', array['Brillo intenso y negro profundo.', 'Capa protectora duradera.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'fresh', '{}'::jsonb, 24);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'llantas-galon'), 'unica', null, 'Galón', '/img/llantas_gal.webp', 'LLANTAS-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('llantas-20-l', 'llantas', 'Abrillantador de Llantas 20 L', 'Abrillantador de Llantas', '20 L', 'auto', 1050.00, 'Fórmula avanzada que limpia, restaura y protege, dejando tus llantas con un brillo intenso y un negro profundo. Combate suciedad y crea una capa protectora duradera para un acabado impecable.', array['Brillo intenso y negro profundo.', 'Capa protectora duradera.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'fresh', '{}'::jsonb, 25);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'llantas-20-l'), 'unica', null, '20 L', '/img/llantas_20.webp', 'LLANTAS-20-L-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('tableros-740-ml', 'tableros', 'Abrillantador de Tableros 740 ml', 'Abrillantador de Tableros', '740 ml', 'auto', 80.00, 'Dale brillo y protección a los tableros de tu vehículo con nuestra fórmula avanzada que repele el polvo, protege contra rayos UV y deja un acabado impecable. Ideal para interiores de autos que quieren lucir como nuevos.', array['Repele el polvo.', 'Protección contra rayos UV.', 'Acabado impecable.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'vainilla', '{}'::jsonb, 26);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'tableros-740-ml'), 'unica', null, '740 ml', '/img/tableros_740.webp', 'TABLEROS-740-ML-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('tableros-galon', 'tableros', 'Abrillantador de Tableros Galón', 'Abrillantador de Tableros', 'Galón', 'auto', 230.00, 'Dale brillo y protección a los tableros de tu vehículo con nuestra fórmula avanzada que repele el polvo, protege contra rayos UV y deja un acabado impecable. Ideal para interiores de autos que quieren lucir como nuevos.', array['Repele el polvo.', 'Protección contra rayos UV.', 'Acabado impecable.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'vainilla', '{}'::jsonb, 27);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'tableros-galon'), 'unica', null, 'Galón', '/img/tableros_gal.webp', 'TABLEROS-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('tableros-20-l', 'tableros', 'Abrillantador de Tableros 20 L', 'Abrillantador de Tableros', '20 L', 'auto', 1100.00, 'Dale brillo y protección a los tableros de tu vehículo con nuestra fórmula avanzada que repele el polvo, protege contra rayos UV y deja un acabado impecable. Ideal para interiores de autos que quieren lucir como nuevos.', array['Repele el polvo.', 'Protección contra rayos UV.', 'Acabado impecable.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], false, false, '{}'::text[], 'vainilla', '{}'::jsonb, 28);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'tableros-20-l'), 'unica', null, '20 L', '/img/tableros_20.webp', 'TABLEROS-20-L-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('motores-galon', 'motores', 'Desengrasante de Motores y Mecánica Galón', 'Desengrasante de Motores y Mecánica', 'Galón', 'auto', 190.00, 'Potente desengrasante que utiliza una combinación de detergentes y agentes activos para eliminar fácilmente la grasa, aceite quemado y residuos acumulados en motores, herramientas y piezas mecánicas.', array['Elimina grasa, aceite quemado y residuos acumulados.', 'Para motores, herramientas y piezas mecánicas.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], true, false, '{}'::text[], 'citronella', '{}'::jsonb, 29);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'motores-galon'), 'unica', null, 'Galón', '/img/motores_gal.webp', 'MOTORES-GALON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('motores-20-l', 'motores', 'Desengrasante de Motores y Mecánica 20 L', 'Desengrasante de Motores y Mecánica', '20 L', 'auto', 900.00, 'Potente desengrasante que utiliza una combinación de detergentes y agentes activos para eliminar fácilmente la grasa, aceite quemado y residuos acumulados en motores, herramientas y piezas mecánicas.', array['Elimina grasa, aceite quemado y residuos acumulados.', 'Para motores, herramientas y piezas mecánicas.']::text[], array['Diluye según la etiqueta o aplica directo en presentaciones listas para usar.', 'Aplica sobre la superficie, deja actuar y enjuaga o retira con microfibra.']::text[], true, false, '{}'::text[], 'citronella', '{}'::jsonb, 30);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'motores-20-l'), 'unica', null, '20 L', '/img/motores_20.webp', 'MOTORES-20-L-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('escoba', 'escoba', 'Escoba completa', 'Escoba completa', 'Unidad', 'articulos', 95.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 31);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'escoba'), 'unica', null, 'Unidad', '/img/escoba.webp', 'ESCOBA-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('mecha', 'mecha', 'Mecha y palo de trapeador', 'Mecha y palo de trapeador', 'Unidad', 'articulos', 120.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 32);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'mecha'), 'unica', null, 'Unidad', '/img/mecha.webp', 'MECHA-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('papel-jumbo', 'papel-jumbo', 'Papel higiénico Jumbo', 'Papel higiénico Jumbo', 'Paquete', 'articulos', 480.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 33);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'papel-jumbo'), 'unica', null, 'Paquete', '/img/papel_jumbo.webp', 'PAPEL-JUMBO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('toalla-rollo', 'toalla-rollo', 'Papel toalla en rollo', 'Papel toalla en rollo', 'Rollo', 'articulos', 380.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 34);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'toalla-rollo'), 'unica', null, 'Rollo', '/img/toalla_rollo.webp', 'TOALLA-ROLLO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('toalla-inter', 'toalla-inter', 'Papel toalla interfoliado', 'Papel toalla interfoliado', 'Caja', 'articulos', 520.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 35);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'toalla-inter'), 'unica', null, 'Caja', '/img/toalla_inter.webp', 'TOALLA-INTER-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('bolsas', 'bolsas', 'Bolsas de basura', 'Bolsas de basura', 'Paquete', 'articulos', 65.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 36);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'bolsas'), 'unica', null, 'Paquete', '/img/bolsas.webp', 'BOLSAS-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('tapetes', 'tapetes', 'Tapetes para urinario', 'Tapetes para urinario', 'Unidad', 'articulos', 75.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 37);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'tapetes'), 'unica', null, 'Unidad', '/img/tapete.webp', 'TAPETES-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('pastes', 'pastes', 'Pastes', 'Pastes', 'Paquete', 'articulos', 45.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 38);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'pastes'), 'unica', null, 'Paquete', '/img/pastes.webp', 'PASTES-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('disp-toalla', 'disp-toalla', 'Dispensador de papel toalla en rollo', 'Dispensador de papel toalla en rollo', 'Unidad', 'dispensadores', 1250.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 39);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'disp-toalla'), 'unica', null, 'Unidad', '/img/disp_toalla.webp', 'DISP-TOALLA-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('disp-higienico', 'disp-higienico', 'Dispensador de papel higiénico', 'Dispensador de papel higiénico', 'Unidad', 'dispensadores', 950.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 40);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'disp-higienico'), 'unica', null, 'Unidad', '/img/disp_hig.webp', 'DISP-HIGIENICO-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('disp-jabon', 'disp-jabon', 'Dispensador de jabón automático', 'Dispensador de jabón automático', 'Unidad', 'dispensadores', 1450.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 41);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'disp-jabon'), 'unica', null, 'Unidad', '/img/disp_jabon.webp', 'DISP-JABON-UNICA', 30, 0);

insert into public.productos (slug, linea, nombre, nombre_base, tamano, categoria_id, precio, descripcion, beneficios, modo_uso, seguridad, cotizar, insignias, tinte, notas, orden) values ('disp-inter', 'disp-inter', 'Dispensador de papel toalla interfoliado', 'Dispensador de papel toalla interfoliado', 'Unidad', 'dispensadores', 850.00, '', '{}'::text[], '{}'::text[], false, false, '{}'::text[], null, '{}'::jsonb, 42);
insert into public.variantes (producto_id, clave, aroma_id, etiqueta, img, sku, stock, orden) values
  ((select id from public.productos where slug = 'disp-inter'), 'unica', null, 'Unidad', '/img/disp_inter.webp', 'DISP-INTER-UNICA', 30, 0);

insert into public.configuracion (banco, tipo_cuenta, numero_cuenta, titular, envio_sps, envio_resto)
values ('Banco Atlántida', 'Cuenta de ahorro en Lempiras', '2001-0045-6789', 'BIOPUREX', 60, 150)
on conflict (id) do nothing;
